module.exports = {
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ['spellcheck', 'react-hooks', 'import', 'react', 'jsx-a11y'],
  rules: {
    'spellcheck/spell-checker': [
      'error',
      {
        identifiers: false,
        ignoreRequire: true,
        skipWords: [
          'advisor',
          'ansible',
          'auditd',
          'camelcase',
          'cdn',
          'checkbox',
          'cpol',
          'csrf',
          'cryptopol',
          'cve',
          'cves',
          'db',
          'donut',
          'dropdown',
          'flyout',
          'hardening',
          'hostid',
          'hostnames',
          'href',
          'iframe',
          'iop',
          'ips',
          'ipv4',
          'jed',
          'jsx',
          'katello',
          'knowledgebase',
          'krb5',
          'noopener',
          'noreferrer',
          'nowrap',
          'openssh',
          'pathname',
          'pid',
          'redhat',
          'redux',
          'rebootable',
          'remediate',
          'remediations',
          'repo',
          'rhc',
          'rulename',
          'scalprum',
          'theforeman',
          'tooltip',
          'unmount',
          'vnd',
          'vuln',
        ],
        minLength: 3,
      },
    ],
  },
};
