export const REPORT_GENERATE_LOGS_POLLING =
  'YUPANA/REPORT_GENERATE_LOGS_POLLING';
export const REPORT_GENERATE_START = 'YUPANA/REPORT_GENERATE_START';
export const REPORT_GENERATE_STOP = 'YUPANA/REPORT_GENERATE_STOP';
export const REPORT_GENERATE_FINISH = 'YUPANA/REPORT_GENERATE_FINISH';
