export const REPORT_GENERATE_LOGS_POLLING =
  'YUPANA/REPORT_GENERATE_LOGS_POLLING';
export const REPORT_GENERATE_LOGS_POLLING_START =
  'YUPANA/REPORT_GENERATE_LOGS_POLLING_START';
export const REPORT_GENERATE_LOGS_POLLING_STOP =
  'YUPANA/REPORT_GENERATE_LOGS_POLLING_STOP';
export const REPORT_GENERATE_PROCESS_START =
  'YUPANA/REPORT_GENERATE_PROCESS_START';
export const REPORT_GENERATE_PROCESS_STOP =
  'YUPANA/REPORT_GENERATE_PROCESS_STOP';
export const REPORT_GENERATE_PROCESS_FINISH =
  'YUPANA/REPORT_GENERATE_PROCESS_FINISH';
export const REPORT_GENERATE_PROCESS_RESTART =
  'YUPANA/REPORT_GENERATE_PROCESS_RESTART';
