export const YUPANA_POLLING = 'YUPANA_POLLING';
export const YUPANA_POLLING_START = 'YUPANA_POLLING_START';
export const YUPANA_POLLING_STOP = 'YUPANA_POLLING_STOP';
export const YUPANA_TAB_CHANGED = 'YUPANA_TAB_CHANGED';
