export const INVENTORY_ACCOUNT_STATUS_POLLING = 'INVENTORY_ACCOUNT_STATUS_POLLING';
export const INVENTORY_ACCOUNT_STATUS_POLLING_ERROR =
  'INVENTORY_ACCOUNT_STATUS_POLLING_ERROR';
export const INVENTORY_ACCOUNT_STATUS_POLLING_START =
  'INVENTORY_ACCOUNT_STATUS_POLLING_START';
export const INVENTORY_ACCOUNT_STATUS_POLLING_STOP =
  'INVENTORY_ACCOUNT_STATUS_POLLING_STOP';
