export const INVENTORY_POLLING = 'INVENTORY_POLLING';
export const INVENTORY_POLLING_START = 'INVENTORY_POLLING_START';
export const INVENTORY_POLLING_STOP = 'INVENTORY_POLLING_STOP';
export const INVENTORY_POLLING_ERROR = 'INVENTORY_POLLING_ERROR';
export const INVENTORY_TAB_CHANGED = 'INVENTORY_TAB_CHANGED';
export const INVENTORY_REPORTS_DOWNLOAD = 'INVENTORY_REPORTS_DOWNLOAD';
export const INVENTORY_PROCESS_RESTART = 'INVENTORY_PROCESS_RESTART';
