export const YUPANA_ACCOUNT_STATUS_POLLING = 'YUPANA_ACCOUNT_STATUS_POLLING';
export const YUPANA_ACCOUNT_STATUS_POLLING_ERROR =
  'YUPANA_ACCOUNT_STATUS_POLLING_ERROR';
export const YUPANA_ACCOUNT_STATUS_POLLING_START =
  'YUPANA_ACCOUNT_STATUS_POLLING_START';
export const YUPANA_ACCOUNT_STATUS_POLLING_STOP =
  'YUPANA_ACCOUNT_STATUS_POLLING_STOP';
