export const REPORT_UPLOAD_PROCESS_START = 'YUPANA/REPORT_UPLOAD_PROCESS_START';
export const REPORT_UPLOAD_PROCESS_STOP = 'YUPANA/REPORT_UPLOAD_PROCESS_STOP';
export const REPORT_UPLOAD_PROCESS_FINISH =
  'YUPANA/REPORT_UPLOAD_PROCESS_FINISH';
export const REPORT_UPLOAD_PROCESS_RESTART =
  'YUPANA/REPORT_UPLOAD_PROCESS_RESTART';
