export const INSIGHTS_SYNC_SETTING_SET = 'INSIGHTS_SYNC_SETTING_SET';

export const INSIGHTS_SYNC_SETTING_SET_FAILURE =
  'INSIGHTS_SYNC_SETTING_SET_FAILURE';

export const INSIGHTS_SYNC_SETTINGS_GET_SUCCESS =
  'INSIGHTS_SYNC_SETTINGS_GET_SUCCESS';

export const INSIGHTS_SYNC_SETTINGS_GET_FAILURE =
  'INSIGHTS_SYNC_SETTINGS_GET_FAILURE';
