name: JS

permissions:
  contents: read

on:
  push:
    branches:
      - 3.18-stable
  pull_request:

jobs:
  test_js:
    name: JavaScript
    uses: theforeman/actions/.github/workflows/foreman_plugin_js.yml@v0
    with:
      plugin: foreman_rh_cloud
      foreman_version: 3.18-stable
