name: Assert Single Commit (non-blocking)

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 30
    - name: Checkout base branch
      run: git fetch origin ${{ github.base_ref }}
    - name: Create local base branch
      run: git branch base_branch origin/${{ github.base_ref }}
    - name: Commit Count Check
      run: test `git log  --oneline --no-merges HEAD ^base_branch | wc -l ` = 1